/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminChurchesRouteImport } from './routes/admin/churches'
import { Route as AdminCommunityRouteImport } from './routes/admin/community'
import { Route as AdminDevotionsRouteImport } from './routes/admin/devotions'
import { Route as AdminDonationsRouteImport } from './routes/admin/donations'
import { Route as AdminGrowthRouteImport } from './routes/admin/growth'
import { Route as AdminJourneysRouteImport } from './routes/admin/journeys'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMusicRouteImport } from './routes/admin/music'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVersesRouteImport } from './routes/admin/verses'
import { Route as AdminWorkoutsRouteImport } from './routes/admin/workouts'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCommunityRouteImport } from './routes/app/community'
import { Route as AppCommunityAccessRouteImport } from './routes/app/community-access'
import { Route as AppJournalRouteImport } from './routes/app/journal'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppTrainRouteImport } from './routes/app/train'
import { Route as AppWakeRouteImport } from './routes/app/wake'
import { Route as GiveIndexRouteImport } from './routes/give/index'
import { Route as GiveThanksRouteImport } from './routes/give/thanks'
import { Route as AppBibleIndexRouteImport } from './routes/app/bible/index'
import { Route as AppChurchIndexRouteImport } from './routes/app/church/index'
import { Route as AppChurchNewRouteImport } from './routes/app/church/new'
import { Route as AppCommunityIndexRouteImport } from './routes/app/community/index'
import { Route as AppCommunityNewRouteImport } from './routes/app/community/new'
import { Route as AppJournalIndexRouteImport } from './routes/app/journal/index'
import { Route as AppJournalPrayerRouteImport } from './routes/app/journal/prayer'
import { Route as AppPlansIndexRouteImport } from './routes/app/plans/index'
import { Route as AppPlansIdRouteImport } from './routes/app/plans/$id'
import { Route as AppWalkIndexRouteImport } from './routes/app/walk/index'
import { Route as AppWorkoutSlugRouteImport } from './routes/app/workout.$slug'
import { Route as AppBibleBookChapterRouteImport } from './routes/app/bible/$book.$chapter'
import { Route as AppChurchIdIndexRouteImport } from './routes/app/church/$id.index'
import { Route as AppChurchIdManageRouteImport } from './routes/app/church/$id.manage'
import { Route as AppChurchJoinCodeRouteImport } from './routes/app/church/join.$code'
import { Route as AppCommunityGroupIdIndexRouteImport } from './routes/app/community/$groupId.index'
import { Route as AppCommunityGroupIdLiveRouteImport } from './routes/app/community/$groupId.live'
import { Route as AppJournalMemoryIndexRouteImport } from './routes/app/journal/memory.index'
import { Route as AppJournalMemoryIdRouteImport } from './routes/app/journal/memory.$id'
import { Route as AppPlansJoinCodeRouteImport } from './routes/app/plans/join.$code'
import { Route as AppWalkJoinCodeRouteImport } from './routes/app/walk/join.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChurchesRoute = AdminChurchesRouteImport.update({
  id: '/churches',
  path: '/churches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevotionsRoute = AdminDevotionsRouteImport.update({
  id: '/devotions',
  path: '/devotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrowthRoute = AdminGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJourneysRoute = AdminJourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMusicRoute = AdminMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVersesRoute = AdminVersesRouteImport.update({
  id: '/verses',
  path: '/verses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkoutsRoute = AdminWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityAccessRoute = AppCommunityAccessRouteImport.update({
  id: '/community-access',
  path: '/community-access',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainRoute = AppTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => AppRoute,
} as any)
const AppWakeRoute = AppWakeRouteImport.update({
  id: '/wake',
  path: '/wake',
  getParentRoute: () => AppRoute,
} as any)
const GiveIndexRoute = GiveIndexRouteImport.update({
  id: '/give/',
  path: '/give/',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveThanksRoute = GiveThanksRouteImport.update({
  id: '/give/thanks',
  path: '/give/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBibleIndexRoute = AppBibleIndexRouteImport.update({
  id: '/bible/',
  path: '/bible/',
  getParentRoute: () => AppRoute,
} as any)
const AppChurchIndexRoute = AppChurchIndexRouteImport.update({
  id: '/church/',
  path: '/church/',
  getParentRoute: () => AppRoute,
} as any)
const AppChurchNewRoute = AppChurchNewRouteImport.update({
  id: '/church/new',
  path: '/church/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityIndexRoute = AppCommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCommunityRoute,
} as any)
const AppCommunityNewRoute = AppCommunityNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCommunityRoute,
} as any)
const AppJournalIndexRoute = AppJournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJournalRoute,
} as any)
const AppJournalPrayerRoute = AppJournalPrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => AppJournalRoute,
} as any)
const AppPlansIndexRoute = AppPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansIdRoute = AppPlansIdRouteImport.update({
  id: '/plans/$id',
  path: '/plans/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppWalkIndexRoute = AppWalkIndexRouteImport.update({
  id: '/walk/',
  path: '/walk/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutSlugRoute = AppWorkoutSlugRouteImport.update({
  id: '/workout/$slug',
  path: '/workout/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBibleBookChapterRoute = AppBibleBookChapterRouteImport.update({
  id: '/bible/$book/$chapter',
  path: '/bible/$book/$chapter',
  getParentRoute: () => AppRoute,
} as any)
const AppChurchIdIndexRoute = AppChurchIdIndexRouteImport.update({
  id: '/church/$id/',
  path: '/church/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppChurchIdManageRoute = AppChurchIdManageRouteImport.update({
  id: '/church/$id/manage',
  path: '/church/$id/manage',
  getParentRoute: () => AppRoute,
} as any)
const AppChurchJoinCodeRoute = AppChurchJoinCodeRouteImport.update({
  id: '/church/join/$code',
  path: '/church/join/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityGroupIdIndexRoute =
  AppCommunityGroupIdIndexRouteImport.update({
    id: '/$groupId/',
    path: '/$groupId/',
    getParentRoute: () => AppCommunityRoute,
  } as any)
const AppCommunityGroupIdLiveRoute = AppCommunityGroupIdLiveRouteImport.update({
  id: '/$groupId/live',
  path: '/$groupId/live',
  getParentRoute: () => AppCommunityRoute,
} as any)
const AppJournalMemoryIndexRoute = AppJournalMemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => AppJournalRoute,
} as any)
const AppJournalMemoryIdRoute = AppJournalMemoryIdRouteImport.update({
  id: '/memory/$id',
  path: '/memory/$id',
  getParentRoute: () => AppJournalRoute,
} as any)
const AppPlansJoinCodeRoute = AppPlansJoinCodeRouteImport.update({
  id: '/plans/join/$code',
  path: '/plans/join/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppWalkJoinCodeRoute = AppWalkJoinCodeRouteImport.update({
  id: '/walk/join/$code',
  path: '/walk/join/$code',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/churches': typeof AdminChurchesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/devotions': typeof AdminDevotionsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/journeys': typeof AdminJourneysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/music': typeof AdminMusicRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verses': typeof AdminVersesRoute
  '/admin/workouts': typeof AdminWorkoutsRoute
  '/app/community': typeof AppCommunityRouteWithChildren
  '/app/community-access': typeof AppCommunityAccessRoute
  '/app/journal': typeof AppJournalRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/train': typeof AppTrainRoute
  '/app/wake': typeof AppWakeRoute
  '/give/thanks': typeof GiveThanksRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/give/': typeof GiveIndexRoute
  '/app/church/new': typeof AppChurchNewRoute
  '/app/community/new': typeof AppCommunityNewRoute
  '/app/journal/prayer': typeof AppJournalPrayerRoute
  '/app/plans/$id': typeof AppPlansIdRoute
  '/app/workout/$slug': typeof AppWorkoutSlugRoute
  '/app/bible/': typeof AppBibleIndexRoute
  '/app/church/': typeof AppChurchIndexRoute
  '/app/community/': typeof AppCommunityIndexRoute
  '/app/journal/': typeof AppJournalIndexRoute
  '/app/plans/': typeof AppPlansIndexRoute
  '/app/walk/': typeof AppWalkIndexRoute
  '/app/bible/$book/$chapter': typeof AppBibleBookChapterRoute
  '/app/church/$id/manage': typeof AppChurchIdManageRoute
  '/app/church/join/$code': typeof AppChurchJoinCodeRoute
  '/app/community/$groupId/live': typeof AppCommunityGroupIdLiveRoute
  '/app/journal/memory/$id': typeof AppJournalMemoryIdRoute
  '/app/plans/join/$code': typeof AppPlansJoinCodeRoute
  '/app/walk/join/$code': typeof AppWalkJoinCodeRoute
  '/app/church/$id/': typeof AppChurchIdIndexRoute
  '/app/community/$groupId/': typeof AppCommunityGroupIdIndexRoute
  '/app/journal/memory/': typeof AppJournalMemoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/churches': typeof AdminChurchesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/devotions': typeof AdminDevotionsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/journeys': typeof AdminJourneysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/music': typeof AdminMusicRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verses': typeof AdminVersesRoute
  '/admin/workouts': typeof AdminWorkoutsRoute
  '/app/community-access': typeof AppCommunityAccessRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/train': typeof AppTrainRoute
  '/app/wake': typeof AppWakeRoute
  '/give/thanks': typeof GiveThanksRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/give': typeof GiveIndexRoute
  '/app/church/new': typeof AppChurchNewRoute
  '/app/community/new': typeof AppCommunityNewRoute
  '/app/journal/prayer': typeof AppJournalPrayerRoute
  '/app/plans/$id': typeof AppPlansIdRoute
  '/app/workout/$slug': typeof AppWorkoutSlugRoute
  '/app/bible': typeof AppBibleIndexRoute
  '/app/church': typeof AppChurchIndexRoute
  '/app/community': typeof AppCommunityIndexRoute
  '/app/journal': typeof AppJournalIndexRoute
  '/app/plans': typeof AppPlansIndexRoute
  '/app/walk': typeof AppWalkIndexRoute
  '/app/bible/$book/$chapter': typeof AppBibleBookChapterRoute
  '/app/church/$id/manage': typeof AppChurchIdManageRoute
  '/app/church/join/$code': typeof AppChurchJoinCodeRoute
  '/app/community/$groupId/live': typeof AppCommunityGroupIdLiveRoute
  '/app/journal/memory/$id': typeof AppJournalMemoryIdRoute
  '/app/plans/join/$code': typeof AppPlansJoinCodeRoute
  '/app/walk/join/$code': typeof AppWalkJoinCodeRoute
  '/app/church/$id': typeof AppChurchIdIndexRoute
  '/app/community/$groupId': typeof AppCommunityGroupIdIndexRoute
  '/app/journal/memory': typeof AppJournalMemoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/churches': typeof AdminChurchesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/devotions': typeof AdminDevotionsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/journeys': typeof AdminJourneysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/music': typeof AdminMusicRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verses': typeof AdminVersesRoute
  '/admin/workouts': typeof AdminWorkoutsRoute
  '/app/community': typeof AppCommunityRouteWithChildren
  '/app/community-access': typeof AppCommunityAccessRoute
  '/app/journal': typeof AppJournalRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/train': typeof AppTrainRoute
  '/app/wake': typeof AppWakeRoute
  '/give/thanks': typeof GiveThanksRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/give/': typeof GiveIndexRoute
  '/app/church/new': typeof AppChurchNewRoute
  '/app/community/new': typeof AppCommunityNewRoute
  '/app/journal/prayer': typeof AppJournalPrayerRoute
  '/app/plans/$id': typeof AppPlansIdRoute
  '/app/workout/$slug': typeof AppWorkoutSlugRoute
  '/app/bible/': typeof AppBibleIndexRoute
  '/app/church/': typeof AppChurchIndexRoute
  '/app/community/': typeof AppCommunityIndexRoute
  '/app/journal/': typeof AppJournalIndexRoute
  '/app/plans/': typeof AppPlansIndexRoute
  '/app/walk/': typeof AppWalkIndexRoute
  '/app/bible/$book/$chapter': typeof AppBibleBookChapterRoute
  '/app/church/$id/manage': typeof AppChurchIdManageRoute
  '/app/church/join/$code': typeof AppChurchJoinCodeRoute
  '/app/community/$groupId/live': typeof AppCommunityGroupIdLiveRoute
  '/app/journal/memory/$id': typeof AppJournalMemoryIdRoute
  '/app/plans/join/$code': typeof AppPlansJoinCodeRoute
  '/app/walk/join/$code': typeof AppWalkJoinCodeRoute
  '/app/church/$id/': typeof AppChurchIdIndexRoute
  '/app/community/$groupId/': typeof AppCommunityGroupIdIndexRoute
  '/app/journal/memory/': typeof AppJournalMemoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin/audit'
    | '/admin/churches'
    | '/admin/community'
    | '/admin/devotions'
    | '/admin/donations'
    | '/admin/growth'
    | '/admin/journeys'
    | '/admin/login'
    | '/admin/music'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verses'
    | '/admin/workouts'
    | '/app/community'
    | '/app/community-access'
    | '/app/journal'
    | '/app/notifications'
    | '/app/profile'
    | '/app/train'
    | '/app/wake'
    | '/give/thanks'
    | '/admin/'
    | '/app/'
    | '/give/'
    | '/app/church/new'
    | '/app/community/new'
    | '/app/journal/prayer'
    | '/app/plans/$id'
    | '/app/workout/$slug'
    | '/app/bible/'
    | '/app/church/'
    | '/app/community/'
    | '/app/journal/'
    | '/app/plans/'
    | '/app/walk/'
    | '/app/bible/$book/$chapter'
    | '/app/church/$id/manage'
    | '/app/church/join/$code'
    | '/app/community/$groupId/live'
    | '/app/journal/memory/$id'
    | '/app/plans/join/$code'
    | '/app/walk/join/$code'
    | '/app/church/$id/'
    | '/app/community/$groupId/'
    | '/app/journal/memory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin/audit'
    | '/admin/churches'
    | '/admin/community'
    | '/admin/devotions'
    | '/admin/donations'
    | '/admin/growth'
    | '/admin/journeys'
    | '/admin/login'
    | '/admin/music'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verses'
    | '/admin/workouts'
    | '/app/community-access'
    | '/app/notifications'
    | '/app/profile'
    | '/app/train'
    | '/app/wake'
    | '/give/thanks'
    | '/admin'
    | '/app'
    | '/give'
    | '/app/church/new'
    | '/app/community/new'
    | '/app/journal/prayer'
    | '/app/plans/$id'
    | '/app/workout/$slug'
    | '/app/bible'
    | '/app/church'
    | '/app/community'
    | '/app/journal'
    | '/app/plans'
    | '/app/walk'
    | '/app/bible/$book/$chapter'
    | '/app/church/$id/manage'
    | '/app/church/join/$code'
    | '/app/community/$groupId/live'
    | '/app/journal/memory/$id'
    | '/app/plans/join/$code'
    | '/app/walk/join/$code'
    | '/app/church/$id'
    | '/app/community/$groupId'
    | '/app/journal/memory'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin/audit'
    | '/admin/churches'
    | '/admin/community'
    | '/admin/devotions'
    | '/admin/donations'
    | '/admin/growth'
    | '/admin/journeys'
    | '/admin/login'
    | '/admin/music'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verses'
    | '/admin/workouts'
    | '/app/community'
    | '/app/community-access'
    | '/app/journal'
    | '/app/notifications'
    | '/app/profile'
    | '/app/train'
    | '/app/wake'
    | '/give/thanks'
    | '/admin/'
    | '/app/'
    | '/give/'
    | '/app/church/new'
    | '/app/community/new'
    | '/app/journal/prayer'
    | '/app/plans/$id'
    | '/app/workout/$slug'
    | '/app/bible/'
    | '/app/church/'
    | '/app/community/'
    | '/app/journal/'
    | '/app/plans/'
    | '/app/walk/'
    | '/app/bible/$book/$chapter'
    | '/app/church/$id/manage'
    | '/app/church/join/$code'
    | '/app/community/$groupId/live'
    | '/app/journal/memory/$id'
    | '/app/plans/join/$code'
    | '/app/walk/join/$code'
    | '/app/church/$id/'
    | '/app/community/$groupId/'
    | '/app/journal/memory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuidelinesRoute: typeof GuidelinesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  GiveThanksRoute: typeof GiveThanksRoute
  GiveIndexRoute: typeof GiveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/churches': {
      id: '/admin/churches'
      path: '/churches'
      fullPath: '/admin/churches'
      preLoaderRoute: typeof AdminChurchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devotions': {
      id: '/admin/devotions'
      path: '/devotions'
      fullPath: '/admin/devotions'
      preLoaderRoute: typeof AdminDevotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/growth': {
      id: '/admin/growth'
      path: '/growth'
      fullPath: '/admin/growth'
      preLoaderRoute: typeof AdminGrowthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/journeys': {
      id: '/admin/journeys'
      path: '/journeys'
      fullPath: '/admin/journeys'
      preLoaderRoute: typeof AdminJourneysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/music': {
      id: '/admin/music'
      path: '/music'
      fullPath: '/admin/music'
      preLoaderRoute: typeof AdminMusicRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verses': {
      id: '/admin/verses'
      path: '/verses'
      fullPath: '/admin/verses'
      preLoaderRoute: typeof AdminVersesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workouts': {
      id: '/admin/workouts'
      path: '/workouts'
      fullPath: '/admin/workouts'
      preLoaderRoute: typeof AdminWorkoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community-access': {
      id: '/app/community-access'
      path: '/community-access'
      fullPath: '/app/community-access'
      preLoaderRoute: typeof AppCommunityAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/train': {
      id: '/app/train'
      path: '/train'
      fullPath: '/app/train'
      preLoaderRoute: typeof AppTrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wake': {
      id: '/app/wake'
      path: '/wake'
      fullPath: '/app/wake'
      preLoaderRoute: typeof AppWakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/give/': {
      id: '/give/'
      path: '/give'
      fullPath: '/give/'
      preLoaderRoute: typeof GiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give/thanks': {
      id: '/give/thanks'
      path: '/give/thanks'
      fullPath: '/give/thanks'
      preLoaderRoute: typeof GiveThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/bible/': {
      id: '/app/bible/'
      path: '/bible'
      fullPath: '/app/bible/'
      preLoaderRoute: typeof AppBibleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/church/': {
      id: '/app/church/'
      path: '/church'
      fullPath: '/app/church/'
      preLoaderRoute: typeof AppChurchIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/church/new': {
      id: '/app/church/new'
      path: '/church/new'
      fullPath: '/app/church/new'
      preLoaderRoute: typeof AppChurchNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community/': {
      id: '/app/community/'
      path: '/'
      fullPath: '/app/community/'
      preLoaderRoute: typeof AppCommunityIndexRouteImport
      parentRoute: typeof AppCommunityRoute
    }
    '/app/community/new': {
      id: '/app/community/new'
      path: '/new'
      fullPath: '/app/community/new'
      preLoaderRoute: typeof AppCommunityNewRouteImport
      parentRoute: typeof AppCommunityRoute
    }
    '/app/journal/': {
      id: '/app/journal/'
      path: '/'
      fullPath: '/app/journal/'
      preLoaderRoute: typeof AppJournalIndexRouteImport
      parentRoute: typeof AppJournalRoute
    }
    '/app/journal/prayer': {
      id: '/app/journal/prayer'
      path: '/prayer'
      fullPath: '/app/journal/prayer'
      preLoaderRoute: typeof AppJournalPrayerRouteImport
      parentRoute: typeof AppJournalRoute
    }
    '/app/plans/': {
      id: '/app/plans/'
      path: '/plans'
      fullPath: '/app/plans/'
      preLoaderRoute: typeof AppPlansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plans/$id': {
      id: '/app/plans/$id'
      path: '/plans/$id'
      fullPath: '/app/plans/$id'
      preLoaderRoute: typeof AppPlansIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/walk/': {
      id: '/app/walk/'
      path: '/walk'
      fullPath: '/app/walk/'
      preLoaderRoute: typeof AppWalkIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workout/$slug': {
      id: '/app/workout/$slug'
      path: '/workout/$slug'
      fullPath: '/app/workout/$slug'
      preLoaderRoute: typeof AppWorkoutSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bible/$book/$chapter': {
      id: '/app/bible/$book/$chapter'
      path: '/bible/$book/$chapter'
      fullPath: '/app/bible/$book/$chapter'
      preLoaderRoute: typeof AppBibleBookChapterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/church/$id/': {
      id: '/app/church/$id/'
      path: '/church/$id'
      fullPath: '/app/church/$id/'
      preLoaderRoute: typeof AppChurchIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/church/$id/manage': {
      id: '/app/church/$id/manage'
      path: '/church/$id/manage'
      fullPath: '/app/church/$id/manage'
      preLoaderRoute: typeof AppChurchIdManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/church/join/$code': {
      id: '/app/church/join/$code'
      path: '/church/join/$code'
      fullPath: '/app/church/join/$code'
      preLoaderRoute: typeof AppChurchJoinCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community/$groupId/': {
      id: '/app/community/$groupId/'
      path: '/$groupId'
      fullPath: '/app/community/$groupId/'
      preLoaderRoute: typeof AppCommunityGroupIdIndexRouteImport
      parentRoute: typeof AppCommunityRoute
    }
    '/app/community/$groupId/live': {
      id: '/app/community/$groupId/live'
      path: '/$groupId/live'
      fullPath: '/app/community/$groupId/live'
      preLoaderRoute: typeof AppCommunityGroupIdLiveRouteImport
      parentRoute: typeof AppCommunityRoute
    }
    '/app/journal/memory/': {
      id: '/app/journal/memory/'
      path: '/memory'
      fullPath: '/app/journal/memory/'
      preLoaderRoute: typeof AppJournalMemoryIndexRouteImport
      parentRoute: typeof AppJournalRoute
    }
    '/app/journal/memory/$id': {
      id: '/app/journal/memory/$id'
      path: '/memory/$id'
      fullPath: '/app/journal/memory/$id'
      preLoaderRoute: typeof AppJournalMemoryIdRouteImport
      parentRoute: typeof AppJournalRoute
    }
    '/app/plans/join/$code': {
      id: '/app/plans/join/$code'
      path: '/plans/join/$code'
      fullPath: '/app/plans/join/$code'
      preLoaderRoute: typeof AppPlansJoinCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/walk/join/$code': {
      id: '/app/walk/join/$code'
      path: '/walk/join/$code'
      fullPath: '/app/walk/join/$code'
      preLoaderRoute: typeof AppWalkJoinCodeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminChurchesRoute: typeof AdminChurchesRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminDevotionsRoute: typeof AdminDevotionsRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminGrowthRoute: typeof AdminGrowthRoute
  AdminJourneysRoute: typeof AdminJourneysRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMusicRoute: typeof AdminMusicRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVersesRoute: typeof AdminVersesRoute
  AdminWorkoutsRoute: typeof AdminWorkoutsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminChurchesRoute: AdminChurchesRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminDevotionsRoute: AdminDevotionsRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminGrowthRoute: AdminGrowthRoute,
  AdminJourneysRoute: AdminJourneysRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMusicRoute: AdminMusicRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVersesRoute: AdminVersesRoute,
  AdminWorkoutsRoute: AdminWorkoutsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCommunityRouteChildren {
  AppCommunityNewRoute: typeof AppCommunityNewRoute
  AppCommunityIndexRoute: typeof AppCommunityIndexRoute
  AppCommunityGroupIdLiveRoute: typeof AppCommunityGroupIdLiveRoute
  AppCommunityGroupIdIndexRoute: typeof AppCommunityGroupIdIndexRoute
}

const AppCommunityRouteChildren: AppCommunityRouteChildren = {
  AppCommunityNewRoute: AppCommunityNewRoute,
  AppCommunityIndexRoute: AppCommunityIndexRoute,
  AppCommunityGroupIdLiveRoute: AppCommunityGroupIdLiveRoute,
  AppCommunityGroupIdIndexRoute: AppCommunityGroupIdIndexRoute,
}

const AppCommunityRouteWithChildren = AppCommunityRoute._addFileChildren(
  AppCommunityRouteChildren,
)

interface AppJournalRouteChildren {
  AppJournalPrayerRoute: typeof AppJournalPrayerRoute
  AppJournalIndexRoute: typeof AppJournalIndexRoute
  AppJournalMemoryIdRoute: typeof AppJournalMemoryIdRoute
  AppJournalMemoryIndexRoute: typeof AppJournalMemoryIndexRoute
}

const AppJournalRouteChildren: AppJournalRouteChildren = {
  AppJournalPrayerRoute: AppJournalPrayerRoute,
  AppJournalIndexRoute: AppJournalIndexRoute,
  AppJournalMemoryIdRoute: AppJournalMemoryIdRoute,
  AppJournalMemoryIndexRoute: AppJournalMemoryIndexRoute,
}

const AppJournalRouteWithChildren = AppJournalRoute._addFileChildren(
  AppJournalRouteChildren,
)

interface AppRouteChildren {
  AppCommunityRoute: typeof AppCommunityRouteWithChildren
  AppCommunityAccessRoute: typeof AppCommunityAccessRoute
  AppJournalRoute: typeof AppJournalRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTrainRoute: typeof AppTrainRoute
  AppWakeRoute: typeof AppWakeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChurchNewRoute: typeof AppChurchNewRoute
  AppPlansIdRoute: typeof AppPlansIdRoute
  AppWorkoutSlugRoute: typeof AppWorkoutSlugRoute
  AppBibleIndexRoute: typeof AppBibleIndexRoute
  AppChurchIndexRoute: typeof AppChurchIndexRoute
  AppPlansIndexRoute: typeof AppPlansIndexRoute
  AppWalkIndexRoute: typeof AppWalkIndexRoute
  AppBibleBookChapterRoute: typeof AppBibleBookChapterRoute
  AppChurchIdManageRoute: typeof AppChurchIdManageRoute
  AppChurchJoinCodeRoute: typeof AppChurchJoinCodeRoute
  AppPlansJoinCodeRoute: typeof AppPlansJoinCodeRoute
  AppWalkJoinCodeRoute: typeof AppWalkJoinCodeRoute
  AppChurchIdIndexRoute: typeof AppChurchIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunityRoute: AppCommunityRouteWithChildren,
  AppCommunityAccessRoute: AppCommunityAccessRoute,
  AppJournalRoute: AppJournalRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppTrainRoute: AppTrainRoute,
  AppWakeRoute: AppWakeRoute,
  AppIndexRoute: AppIndexRoute,
  AppChurchNewRoute: AppChurchNewRoute,
  AppPlansIdRoute: AppPlansIdRoute,
  AppWorkoutSlugRoute: AppWorkoutSlugRoute,
  AppBibleIndexRoute: AppBibleIndexRoute,
  AppChurchIndexRoute: AppChurchIndexRoute,
  AppPlansIndexRoute: AppPlansIndexRoute,
  AppWalkIndexRoute: AppWalkIndexRoute,
  AppBibleBookChapterRoute: AppBibleBookChapterRoute,
  AppChurchIdManageRoute: AppChurchIdManageRoute,
  AppChurchJoinCodeRoute: AppChurchJoinCodeRoute,
  AppPlansJoinCodeRoute: AppPlansJoinCodeRoute,
  AppWalkJoinCodeRoute: AppWalkJoinCodeRoute,
  AppChurchIdIndexRoute: AppChurchIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuidelinesRoute: GuidelinesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  GiveThanksRoute: GiveThanksRoute,
  GiveIndexRoute: GiveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
